# 1.1 NUMPY

In [1]:
import numpy as np

In [18]:

a1 = np.array([1, 2, 3])
print('a1')
print(a1)
print('shape of a1:', a1.shape) # 

print()

a2 = np.array([[1, 2, 3], [4, 5, 6]])
print('a2')
print(a2)
print('shape of a2:', a2.shape) # 2 filas, 3 columnas
print('cantidad de elementos',a2.size)

print()
a3 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print('a3')
print(a3)
print('shape of a3:', a3.shape) # 2 filas, 2 columnas, profunidad 3
print('cantidad de elemenos',a3.size) # 2x2x3



print()
a4 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]], [[10, 20, 30], [40, 50, 60]],
              [[10, 20, 30], [40, 50, 60]]])
print('a4')
print(a4)
print('shape of a4:', a4.shape) # 4-2-3
print('cantidad de elemenos',a4.size) # 4x2x3






a1
[1 2 3]
shape of a1: (3,)

a2
[[1 2 3]
 [4 5 6]]
shape of a2: (2, 3)
cantidad de elementos 6

a3
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
shape of a3: (2, 2, 3)
cantidad de elemenos 12

a4
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[10 20 30]
  [40 50 60]]

 [[10 20 30]
  [40 50 60]]]
shape of a4: (4, 2, 3)
cantidad de elemenos 24


In [22]:
a4.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 10, 20, 30, 40, 50,
       60, 10, 20, 30, 40, 50, 60])

In [29]:
a5 = np.array([
                [
                    [1, 2, 3,7], [4, 5, 6,7], [4, 5, 6,7]
                ], 
                [
                    [7, 8, 9,2], [10, 11, 12,2], [4, 5, 6,7]
                ], 
                [
                    [10, 20, 30,1], [40, 50, 60,1], [4, 5, 6,7]
                ],
                [
                    [10, 20, 30,1], [40, 50, 60,1], [4, 5, 6,7]
                ],
                [
                    [10, 20, 30,1], [40, 50, 60,1], [4, 5, 6,7]
                ]
            ])
print('a5')
print(a5)
print('shape:', a5.shape) 
print('cantidad de elemenos',a5.size) #

a5
[[[ 1  2  3  7]
  [ 4  5  6  7]
  [ 4  5  6  7]]

 [[ 7  8  9  2]
  [10 11 12  2]
  [ 4  5  6  7]]

 [[10 20 30  1]
  [40 50 60  1]
  [ 4  5  6  7]]

 [[10 20 30  1]
  [40 50 60  1]
  [ 4  5  6  7]]

 [[10 20 30  1]
  [40 50 60  1]
  [ 4  5  6  7]]]
shape: (5, 3, 4)
cantidad de elemenos 60


### Reshape

In [36]:
v = np.array([
        [
            [1,2],
            [3,4],
            [6,8]
        ]
])

print('shape de v',v.shape)
print()

f = v.reshape((v.shape[0]*v.shape[1], v.shape[2]))

print('f')
print(f)
print(f.shape)



shape de v (1, 3, 2)

f
[[1 2]
 [3 4]
 [6 8]]
(3, 2)


### Norm

In [62]:

aux = np.array([[ 1, 2, 3],

              [-1, 1, 4]])
print(aux)
print(aux.shape)


"""

axis = 1

sqrt ( 1**2 + 2**2 + 3**2) = 3.74....
sqrt( 1**2 + 1**2 + 4**2) = 4.24.....
"""

np.linalg.norm(aux,ord=2,axis=1,keepdims=True)





[[ 1  2  3]
 [-1  1  4]]
(2, 3)


array([[3.74165739],
       [4.24264069]])

In [65]:
aux = np.array([[ 1, 2, 3],

              [-1, 1, 4]])
print(aux)
print(aux.shape)


"""

axis = 0

sqrt ( 1**2 + -1**2 ) = 1.41....
sqrt( 2**2 + 1**2 ) = 2,23.....
sqrt(3**2+4**2) = 5

"""

np.linalg.norm(aux,ord=2,axis=0,keepdims=True)

[[ 1  2  3]
 [-1  1  4]]
(2, 3)


array([[1.41421356, 2.23606798, 5.        ]])

### operaciones

In [67]:
x1 = [1,2,3]
x2 = [2,4,4]

In [70]:
### producto punto
dot = np.dot(x1,x2)
dot


22

In [72]:
outer = np.outer(x1,x2)
outer

array([[ 2,  4,  4],
       [ 4,  8,  8],
       [ 6, 12, 12]])

In [73]:
# element wise
wise = np.multiply(x1,x2)
wise

array([ 2,  8, 12])

In [75]:

# para multiplicar matrices uso np.dot


a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[1, 7], [2, 2], [3, 12]])

print(np.dot(a,b))


[[ 14  47]
 [ 32 110]]


### indexado


In [4]:
d = np.array([[1,2],[3,4]])

In [5]:
d.shape

(2, 2)

In [7]:
d

array([[1, 2],
       [3, 4]])

In [8]:
d[:,0] # primer columna

array([1, 3])

In [9]:
d[:,1].shape


(2,)

In [10]:
d[:,1]

array([2, 4])

In [11]:
d[1,:] # segunda fila

array([3, 4])